// const { parse } = require('lua-json')
const fs = require("fs")
const Path = require("path")
const parser = require("luaparse")

// const ast = parser.parse("i = 0")
// console.log(JSON.stringify(ast))

const build = fs.readFileSync("build.lua", "utf-8")
// const build = fs.readFileSync(Path.join(__dirname, 'file.lua'), 'utf-8')
// console.log(build)
// console.log(parse(build))
const ast = parser.parse(build)
// console.log(JSON.stringify(ast))
fs.writeFileSync(Path.join(__dirname, "file.json"), JSON.stringify(ast))
